sudo: required
language: python
python:
  - 3.8

env:
  global:
    - APPLICATION_NAME=MyHero

services:
  - docker

before_script:
  - echo $DOCKER_PASSWORD |  docker login -u $DOCKER_ID --password-stdin
  - curl https://cli-assets.heroku.com/install.sh | sh
  - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com

script:
  - docker build -t shysan/myheroflask:v1 .
  - docker tag shysan/myhero:v1 registry.heroku.com/$HEROKU_APP/web

deploy:
  provider: script
  script:
    docker push shysan/myheroflask:v1;
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web -app $HEROKU_APP
  on:
    branch: master